version: '3.8'

volumes:
  db-data:

services:
  api:
    container_name: api
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
    links:
      - db

  db: # service名は、ormconfig.tsのhostの値と同じにする
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    # volumes:
    #   - 'db-data:/var/lib/mysql/data'
